### ISSUE TITLE
Has the helm chart been moved out of here? ... and how about the various Dockerfiles?

### ISSUE THREAD

**Issue by Analect** [data-8/jupyterhub-k8s#176]
I used this repo some months back as a useful reference for deploying jupyterhub on kubernetes.  However, it seems much of the detail has been removed.  The readme references a `./build.bash` script which no longer appears in this repo.

**Comment by ryanlovett** [comment]
Sorry for the missing breadcrumbs! The most up-to-date​ documentation is at https://github.com/jupyterhub/zero-to-jupyterhub-k8s.

The docker containers are at https://github.com/data-8/user-containers.

**Comment by ryanlovett** [comment]
The helm chart is at https://github.com/jupyterhub/helm-chart.

**Comment by Analect** [comment]
Great. Thanks @ryanlovett  ...  do you manage the `values.yaml` and `config.yaml`, as specified in jupyterhub/helm-chart offline?

I was curious to find the [install-demo.bash](https://github.com/data-8/user-containers/blob/master/demo/install-demo.bash) approach to pre-seed compute environments with notebooks from a repo.  I had been experimenting with [git-sync](https://github.com/kubernetes/git-sync/issues/40) ... which works in terms of pulling (everything) .. but doesn't allow pushing back to the remote repo ... something I wanted to be able to have from a spawned pod.  I know you guys just persist all of a user's work to google-drive ... but have you come across any good two-way git solutions from a pod?

**Comment by ryanlovett** [comment]
Yes, we manage site-specific yaml in a local git repo that gets mirrored to a private github instance.

Up until now we've used [nbpuller](https://github.com/data-8/nbpuller) to do one-way syncs. @yuvipanda [has proposed](https://github.com/data-8/nbpuller/issues/43) splitting its functionality into two sub-components. But you're right, we don't have our students push changes back out.

Do you want some unattended process to do the pushing? Or do you want to make it easy for users to initiate the push? The latter could be accomplished by a notebook extension of some sort while the former could be implemented in several different ways. On GCE, [we will manually sync](https://github.com/data-8/jupyterhub-k8s/tree/master/archive) to cold storage, though as you indicated the long term plan is to let an extension sync to Drive.

Am closing this but we can can continue the discussion here, on a new helm-chart issue, or...

@yuvipanda How would you feel about a Google Group to discuss jupyterhub-k8s issues? (akin to jupyter-education) IMO it is cumbersome to get everyone on the uc-jupyter slack.

**Comment by yuvipanda** [comment]
@ryanlovett I'd really like to not have another group. We can just use jupyter-education, issues here, or the jupyter mailing list.

**Comment by Analect** [comment]
@ryanlovett @yuvipanda 
Thank you both for chiming in here.

> Do you want some unattended process to do the pushing? Or do you want to make it easy for users to initiate the push?

Probably the latter ... so I want a user to have the ability to push their changes back to a remote repo ... either in stages ... as they work .. or at the very least as a single commit before they exit a compute environment.

Ideally, yes, this would get added as an extension in jupyterlab ... and get included as either a menu-item or some other UI button.  I'm not sure I have the capability/know-how to do that just yet ... particularly given that the extension mechanism has just landed for jupyterlab ... 

... so in the interim, I just wanted to at least get something manual rigged-up ... what I was contemplating was using this alternative [git-sync](https://github.com/appertly/docker-git-sync/issues/1), where I can avoid the problems I was having with the 'official' git-sync.  I'm using a `secrets` config per user on kubernetes to store the public key to authenticate against a remote repo, which appears to work OK ... and I was going to see about wiring [this](https://github.com/alan0201tw/JupyterNotebook_auto_pop_GUI) up, which 'might' give me a basic UI external to jupyterlab for now ... which leverages the post-save hook in a notebook and would get included in the jupyter_notebook_config.py ... although I don't know if that is going to work for me in jupyterlab ... and linking it directly to just notebooks may not be enough.

I'd be interested in your thoughts on the viability of this.

**Comment by ryanlovett** [comment]
Okay! @Analect let's continue on the jupyter list if there's followup discussion.
