### ISSUE TITLE
Port data8's deployment to k8s

### ISSUE THREAD

**Issue by SamLau95** [data-8/jupyterhub-k8s#3]
This epic is complete when we can deploy something equivalent to Data 8's deployment of JHub on Kubernetes.

**Comment by derrickmar** [comment]
@SamLau95 so far it looks good to me. I'm gonna wait to approve this though and will work off this branch for issue #3 to use the  Makefile to update the image. That'll be our manual testing for this PR.

**Comment by SamLau95** [comment]
@derrickmar did you mean to comment on https://github.com/data-8/jupyterhub-k8s/pull/23 ?

**Comment by derrickmar** [comment]
O  yes yes. Eh my bad

**Comment by SamLau95** [comment]
And we're done with this epic!
