### ISSUE TITLE
Make docker builds faster

### ISSUE THREAD

**Issue by derrickmar** [data-8/jupyterhub-k8s#41]
Currently our Makefile which builds the images (hub, cull, user) whenever there's a push takes on the order of 20 minutes. Brainstorm ideas to make this faster.

https://github.com/travis-ci/travis-ci/issues/5358

**Comment by ryanlovett** [comment]
This may work, https://github.com/travis-ci/travis-ci/issues/5358#issuecomment-186593265. Basically you push every layer to Docker hub (with a tag based on a git hash or some such) and new builds just need to fetch the last, unchanged layer. But then the FROM will wander as you chase the last unchanged layer, which isn't so good.
