### ISSUE TITLE
OAuth client secret is exposed

### ISSUE THREAD

**Issue by ryanlovett** [data-8/jupyterhub-k8s#44]
Re: https://github.com/data-8/jupyterhub-k8s/blob/data8_jupyterhubv3/manifest.yaml#L31

It theoretically could be used to impersonate the OAuth client (the authenticator).

More: https://tools.ietf.org/html/rfc6819#section-4.1.1

**Comment by SamLau95** [comment]
Yeah @derrickmar accidentally committed it. Nothing super serious for now since those keys are only used in development. We'll revoke them when we merge in the changes he has and use a proper config.

**Comment by yuvipanda** [comment]
Not the case anymore :)
