### ISSUE TITLE
Add Google Analytics support

### ISSUE THREAD

**Issue by ryanlovett** [data-8/jupyterhub-k8s#75]
Create a project at Google Analytics, generate a tracking code, and add it to the hub and single user server.

**Comment by yuvipanda** [comment]
What would this be used for?

**Comment by yuvipanda** [comment]
I want to say let's not do this right now for both privacy and other concerns :) Let's discuss what we need analytics to measure and figure it out later.

**Comment by ryanlovett** [comment]
Sorry, I somehow missed your original response.

A student in last semester's course said that a lab or project notebook worked on it for a while had disappeared. We looked at all of our logs but couldn't find any evidence that they ever visited the assignment. I thought that GA might assist us in resolving similar issues in the future.

**Comment by yuvipanda** [comment]
I'm gonna close this for now, let's re-open a more generic analytics ticket later if we want.
