### ISSUE TITLE
"import nibabel" crashes kernel on datahub-dev

### ISSUE THREAD

**Issue by ryanlovett** [data-8/jupyterhub-k8s#83]
It generates output in the logs: 
```
Warning! ***HDF5 library version mismatched error***
The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues.
This can happen when an application was compiled by one version of HDF5 but
linked with a different version of static or shared HDF5 library.
You should recompile the application or check your shared library related
settings such as 'LD_LIBRARY_PATH'.
You can, at your own risk, disable this warning by setting the environment
variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
Setting it to 2 or higher will suppress the warning messages totally.
Headers are 1.8.17, library is 1.8.15
```

We have conda's hdf5 version 1.8.15.1 while 1.8.17 is available. I recommend we try installing nibabel=2.1.0 from conda. tqdm(=4.10.0.) is also in conda.

@choldgraf @marklescroart (I can't find Leila or Fatma's github handles)

**Comment by choldgraf** [comment]
are we installing it with `pip` currently? That strategy sounds good to me.

**Comment by ryanlovett** [comment]
Yes, currently pip.

https://github.com/data-8/jupyterhub-k8s/blob/master/user/connectors/neuro.bash

**Comment by choldgraf** [comment]
I don't see a reason not to install with `conda`, so I think that's fine to use conda

**Comment by yuvipanda** [comment]
Works fine now.

**Comment by engineeringmath** [comment]
Sorry Guys,

I am not an experienced programmer, but I get the same error message when trying to import h5py in Spyder. The error message is below.  Could you pleas  help?  Thanks.


Warning! ***HDF5 library version mismatched error***
The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues.
This can happen when an application was compiled by one version of HDF5 but
linked with a different version of static or shared HDF5 library.
You should recompile the application or check your shared library related
settings such as 'LD_LIBRARY_PATH'.
You can, at your own risk, disable this warning by setting the environment
variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
Setting it to 2 or higher will suppress the warning messages totally.
Headers are 1.8.17, library is 1.8.15
	    SUMMARY OF THE HDF5 CONFIGURATION
	    =================================

General Information:
-------------------
		   HDF5 Version: 1.8.15-patch1
		  Configured on: Tue Aug 25 22:15:09 UTC 2015
		  Configured by: vagrant@localhost.localdomain
		 Configure mode: production
		    Host system: x86_64-unknown-linux-gnu
	      Uname information: Linux localhost.localdomain 2.6.18-398.el5 #1 SMP Tue Sep 16 20:50:52 EDT 2014 x86_64 x86_64 x86_64 GNU/Linux
		       Byte sex: little-endian
		      Libraries: static, shared
	     Installation point: /home/vagrant/miniconda/envs/_build

Compiling Options:
------------------
               Compilation Mode: production
                     C Compiler: /home/vagrant/miniconda/envs/_build/bin/gcc ( gcc (GCC) 4.8.5)
                         CFLAGS: 
                      H5_CFLAGS: -std=c99 -pedantic -Wall -Wextra -Wundef -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wcast-align -Wwrite-strings -Wconversion -Waggregate-return -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wnested-externs -Winline -Wfloat-equal -Wmissing-format-attribute -Wmissing-noreturn -Wpacked -Wdisabled-optimization -Wformat=2 -Wunreachable-code -Wendif-labels -Wdeclaration-after-statement -Wold-style-definition -Winvalid-pch -Wvariadic-macros -Winit-self -Wmissing-include-dirs -Wswitch-default -Wswitch-enum -Wunused-macros -Wunsafe-loop-optimizations -Wc++-compat -Wstrict-overflow -Wlogical-op -Wlarger-than=2048 -Wvla -Wsync-nand -Wframe-larger-than=16384 -Wpacked-bitfield-compat -Wstrict-overflow=5 -Wjump-misses-init -Wunsuffixed-float-constants -Wdouble-promotion -Wsuggest-attribute=const -Wtrampolines -Wstack-usage=8192 -Wvector-operation-performance -Wsuggest-attribute=pure -Wsuggest-attribute=noreturn -Wsuggest-attribute=format -O3 -fomit-frame-pointer -finline-functions
                      AM_CFLAGS: 
                       CPPFLAGS: 
                    H5_CPPFLAGS: -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_GNU_SOURCE -D_POSIX_C_SOURCE=200112L   -DNDEBUG -UH5_DEBUG_API
                    AM_CPPFLAGS: -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE  -I/home/vagrant/miniconda/envs/_build/include
               Shared C Library: yes
               Static C Library: yes
  Statically Linked Executables: no
                        LDFLAGS: 
                     H5_LDFLAGS: 
                     AM_LDFLAGS:  -L/home/vagrant/miniconda/envs/_build/lib
 	 	Extra libraries: -lrt -lz -ldl -lm 
 		       Archiver: ar
 		 	 Ranlib: ranlib
 	      Debugged Packages: 
		    API Tracing: no

Languages:
----------
                        Fortran: no

                            C++: yes
                   C++ Compiler: /home/vagrant/miniconda/envs/_build/bin/g++ ( g++ (GCC) 4.8.5)
                      C++ Flags: 
                   H5 C++ Flags:  
                   AM C++ Flags: 
             Shared C++ Library: yes
             Static C++ Library: yes

Features:
---------
                  Parallel HDF5: no
             High Level library: yes
                   Threadsafety: no
            Default API Mapping: v18
 With Deprecated Public Symbols: yes
         I/O filters (external): deflate(zlib)
                            MPE: no
                     Direct VFD: no
                        dmalloc: no
Clear file buffers before write: yes
           Using memory checker: no
         Function Stack Tracing: no
      Strict File Format Checks: no
   Optimization Instrumentation: no
Bye...

**Comment by choldgraf** [comment]
hey @engineeringmath , I'd recommend opening a new issue for this, rather than adding this information to an older issue. Just click "issues" at the top and then click "new issue".

**Comment by engineeringmath** [comment]
just did
https://github.com/data-8/jupyterhub-k8s/issues/118
thank you.
